/*

Created on 03/2014

Author: guidefloripa

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

*/

#include <stdio.h>

static inline int fibonacci(int term1, int term2)
{
	return term1 + term2;
}

int main(int argc, char** argv)
{
	int term = 2;
	int prev_term = 1;
	int aux;
	int sum = 0;

	while (term < 4000000) {
		if (term%2 == 0) {
			sum += term;
		}
		aux = fibonacci(prev_term, term);
		prev_term = term;
		term = aux;
	}

	fprintf(stdout, "[Problem 02] %d\n", sum);

	return 0;
}
