/*

Created on 03/2014

Author: guidefloripa

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

*/

#include <stdio.h>

#ifndef FASTER_METHOD
#define FASTER_METHOD 1
#endif

typedef unsigned long long uint64_t;

static uint64_t sqrt_uint64_t(uint64_t value)
{
	uint64_t min = 0;
	uint64_t max = ((uint64_t)1) << 32;
	uint64_t sqt;
	uint64_t sq;

	while (1) {
		if (max <= 1 + min)
			return min;

		sqt = min + (max - min)/2;
		sq = sqt*sqt;

		if (sq == value) 
			return sqt;

		if (sq > value)
			max = sqt;
		else
			min = sqt;
	}
}

static int isPrime(uint64_t value)
{
	uint64_t max = sqrt_uint64_t(value)+1;
	for (int i=3; i<max; i+=2) {
		if (value%i==0) return 0;
	}

	return 1;
}

static int n_divisors(uint64_t value)
{
#if FASTER_METHOD
	/* https://brilliant.org/assessment/techniques-trainer/divisors-of-an-integer */
	int n_div = 1;
	int sum = 1;
	int prime = 2;

	if (value<3) return value;

	while (value > 1) {
		sum = 0;
		while (value%prime == 0) {
			sum++;
			value /= prime;
		}
		if (sum > 0) n_div *= (sum+1);
		do {
			prime++;
		} while (!isPrime(prime));
	}

	return n_div;
#else
	uint64_t i;
	uint64_t n = value>1 ? 2 : 1;
	int max = (value/2)+1;
	for (i=2; i<=max; i++) {
		if (value%i==0) {
			n++;
		}
	}
	return n;
#endif
}

int main(int argc, char** argv)
{
	uint64_t n = 1;
	uint64_t current=1;
	int n_div = 0;

	do {
		current += ++n;
		n_div = n_divisors(current);
		fprintf(stderr, "%lld | %lld > %d\n", n, current, n_div);
	} while (n_div < 500);

	fprintf(stderr, "[Problem 12] %lld [%d divisors]\n", current, n_div);

	return 0;
}
